version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/aliahmadhq1/traefik"
  dependencies_vendored = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs",
    "meteor",
    "ember",
    "angular"
  ]

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true